apiVersion: v1
kind: Namespace
metadata:
  name: rook-yugabytedb
---
apiVersion: yugabytedb.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-yugabytedb
  namespace: rook-yugabytedb
spec:
  # Mentioning network ports is optional. If some or all ports are not specified, then they will be defaulted to below mentioned values, except for tserver-ui.
  # For tserver-ui a cluster ip service will be created if the yb-tserver-ui port is explicitly mentioned. If it is not specified, only StatefulSet & headless service will be created for TServer.
  # TServer ClusterIP service creation will be skipped. Whereas for Master, all 3 kubernetes objects will always be created.
  network:
    ports:
      - name: yb-master-ui
        port: 7000          # default value
      - name: yb-master-grpc
        port: 7100          # default value
      - name: yb-tserver-ui
        port: 9000          # default value
      - name: yb-tserver-grpc
        port: 9100          # default value
      - name: yb-tserver-cassandra
        port: 9042          # default value
      - name: yb-tserver-redis
        port: 6379          # default value
      - name: yb-tserver-postgres
        port: 5433          # default value
  # Replica count for master & tserver
  replicas:
    master: 3
    tserver: 3
  scope:
    master:
      volumeClaimTemplates:
      - metadata:
          name: datadir
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
          storageClassName: standard
    tserver:
      volumeClaimTemplates:
      - metadata:
          name: datadir
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
          storageClassName: standard
